# Generated by Django 5.0.7 on 2024-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField()),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
    ]
